services:
  code-server:
    container_name: code-server
    build:
      context: .
      args:
        - USERNAME=${USERNAME:-dereck}
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD}
    volumes:
      - ${DATA_DIR:-/media/nvme0/vscode-server}:/home/${USERNAME:-dereck}
      - ./config:/config
    ports:
      - '8443:8443'
    restart: unless-stopped
    networks:
      - homarr_net

networks:
  homarr_net:
    external: true
