services:
  vscode-server:
    container_name: vscode-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        PORT: ${PORT}
        PASSWORD: ${PASSWORD}
    environment:
      PASSWORD: ${PASSWORD}
      PORT: ${PORT}
      HOME: /home/${USERNAME}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ${HOST_VOLUME}:/home/${USERNAME}
    restart: unless-stopped
    tty: true
