services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - homarr
      - plex
      - kiwix
      - openstreetmap
      - transmission-openvpn
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - home_server
    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - BASE_URL=/homarr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dereck/docker/home-server/services/homarr/content/configs:/app/data/configs
      - /home/dereck/docker/home-server/services/homarr/content/icons:/app/public/icons
      - /home/dereck/docker/home-server/services/homarr/content/data:/data
    networks:
      - home_server

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /media/nvme0/app-data/plex/config:/config
      - /media/nvme0/media:/media
    restart: unless-stopped
    networks:
      - home_server

  kiwix:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve:latest
    volumes:
      - /media/nvme0/app-data/kiwix/zim:/data
    restart: unless-stopped
    command: ['*.zim']
    environment:
      - 'DOWNLOAD=https://download.kiwix.org/zim/wikipedia_bm_all.zim'
    networks:
      - home_server

  openstreetmap:
    container_name: openstreetmap
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-data:/data/database
      - osm-tiles:/data/tiles
      - /mnt/nvme1/app-data/open-street-map:/data
    environment:
      - UPDATES=enabled
      - THREADS=4
      - ALLOW_CORS=enabled
      - PGPASSWORD=your_password
    command: run
    networks:
      - home_server

  transmission-openvpn:
    container_name: TransmissionVPN
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - '/media/nvme0/torrent/:/data'
      - '/media/nvme0/app-data/transmission/:/config'
      - '/home/dereck/Projects/docker/transmission/:/etc/openvpn/custom/'
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_CONFIG=us.protonvpn.tcp
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_RPC_WHITELIST=192.168.*.*,127.0.0.1
    logging:
      driver: json-file
      options:
        max-size: 10m
    image: haugene/transmission-openvpn
    networks:
      - home_server

volumes:
  osm-data:
  osm-tiles:
  letsencrypt:

networks:
  home_server:
    driver: bridge
