services:
  vscode-server:
    image: dereckmezquita/vscode-server-base:latest
    container_name: vscode-server
    ports:
      - "${HOST_PORT}:8080" # Map HOST_PORT to container's port 8080
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - WORKSPACE_DIR=${WORKSPACE_DIR}
      - HOST_PORT=8080
    volumes:
      - ${WORKSPACE_DIR}:${WORKSPACE_DIR} # Mount the workspace directory
